name: itch.io Windows Build

on:
  push:
    branches:
      - main

jobs:
  itch_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: josephbmanley/butler-publish-itchio-action@v1.0.3
      env:
        BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
        CHANNEL: windows
        ITCH_GAME: versionary
        ITCH_USER: versionary
        PACKAGE: windows
